#!/usr/bin/php

<?php

echo "Gif recorder tool\n";
echo "Please move your mousse\n";
echo "at the top left corner point of the wanted gif area.\n\n";
echo "Then press enter.";

#~ Nico KraZhtest | 2017 | php <(curl -s https://ponyhacks.com/open/gif/gif)
#~ Dependencies: php-cli xdotool byzanz-record gifsicle curl
#~ From the home folder, the command to start would be: ./gif
#~ You can set the gif record time as argument: ./gif 10
#~ Default record time is 1 seconde, or set it here:
   $recordTime = 1;
    
if (@$argv[1] == "install") {
    // Clear screen
    echo chr(27).chr(91).'H'.chr(27).chr(91).'J';
    // Get current filename
    $me = basename(__FILE__);
    echo "Installing gif\n";
    // Create hidden folder .cli in home
    system("mkdir -p ./.cli");
     usleep(3000000);
      system("cp -v gif ./.cli");
     usleep(3000000);
    // Copying .cli path
    system("echo \"PATH=\$HOME/.cli:\$PATH\" >> ~/.bash_profile");
     usleep(1000000);
    // Merging folder path
    echo "source ~/.bash_profile";
     usleep(2000000);
    echo "\nDone: Now type gif to launch again.\n";
    echo "Thanks YOU!\n";
    exit;
}

if (@$argv[1] == "update") {
    // Clear screen
    echo chr(27).chr(91).'H'.chr(27).chr(91).'J';
    echo "Updating...\n";
    system("wget -O ./.cli/gif https://ponyhacks.com/open/cli/gif");
    usleep(2000000);
    echo "Updated.\nThanks YOU!\n";
    exit;
}

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));
$t = @$argv[1];

if (!isset($argv[1])) {
  $t = $recordTime;
}

$p1 = system("xdotool getmouselocation");

$pos1 = explode(" ",$p1);

$x1 = $pos1[0];
$x1 = explode(":",$x1);
echo "X1: ".$x1[1];

$y1 = $pos1[1];
$y1 = explode(":",$y1);
echo " Y1: ".$y1[1];

echo "\nNow move your mousse at the bottom right corner.\n";
echo "Then enter.";

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

$p2 = system("xdotool getmouselocation");

$pos2 = explode(" ",$p2);

$x2 = $pos2[0];
$x2 = explode(":",$x2);
echo "X2: ".$x2[1];

$y2 = $pos2[1];
$y2 = explode(":",$y2);
echo " Y2: ".$y2[1];

$gw = ($x2[1] - $x1[1]);
echo "\nGif width: ".$gw;

$gh = ($y2[1] - $y1[1]);
echo "\nGif height: ".$gh;

$unix =  date_timestamp_get(date_create());

echo "\n".$unix." | Starting gif record for ".$t."s\n";

system("byzanz-record --duration=$t --x=$x1[1] --y=$y1[1] --width=$gw --height=$gh ~/Pictures/gif$unix.gif");

$named = "gif".$unix;
echo "Gif saved\n";

system("du -h ~/Pictures/$named.gif");

system("gifsicle --color-info ~/Pictures/$named.gif");

echo "Optimize | How many colors to keep? (default 100) ";

$stdin = fopen('php://stdin', 'r');
$defc = "100";
$response = rtrim(fgets(STDIN));
$defc += $response; 

system("gifsicle --verbose -i ~/Pictures/$named.gif -O5 --colors=$defc -o ~/Pictures/$named\_reduced.gif");

system("du -h ~/Pictures/$named\_reduced.gif");

echo "Optimize | Resize width in pixels (default 300px) ";

$stdin = fopen('php://stdin', 'r');
$rw = "300";
$response = rtrim(fgets(STDIN));

$rw += $response;

system("gifsicle --verbose -i ~/Pictures/$named\_reduced.gif --resize-width $rw -o ~/Pictures/".$named."_optimized.gif");

$opt = "~/Pictures/".$named."_optimized.gif";
    
#~ system("xdg-open $opt");
#~ system("xdg-open $rev");

system("gifsicle --color-info $opt");

$f = system("du -h $opt");

echo "Special | Reverse and merge?";

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

system("gifsicle -i ~/Pictures/$named\_reduced.gif '#-2-1' -o ~/Pictures/".$named."_reversed.gif");

$rev = "~/Pictures/".$named."_reversed.gif";

usleep(400000);

system("gifsicle -i ~/Pictures/$named\_reduced.gif --append $rev --resize-width $rw -o ~/Pictures/".$named."_merged.gif");

system("xdg-open ~/Pictures/".$named."_merged.gif  > /dev/null &");

echo "Upload to giphy?";

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

$f = explode("	",$f);

$f = $f[1];

$www = system('curl --silent -v -F "file=@'.$f.'" -F "api_key=dc6zaTOxFJmzC"  "http://upload.giphy.com/v1/gifs"');

$www = json_decode($www);

echo "\n\n";

echo "https://i.giphy.com/".$www->data->id.".gif";

echo "\nThanks YOU!\n";











