#!/usr/bin/php

<?php
#> php xdotool byzanz gifsicle curl

echo "Usage: ./gif [time in seconds] [install|update]\n";
echo "--------------------------------------------------\n";
echo "Gif recorder tool\n";
echo "Please move your mouse at the top left corner point\n";
echo "of the wanted gif area. Then press enter.\n";
echo "\n";

#~ Nico KraZhtest | 2017 | php <(curl -s https://ponyhacks.com/open/gif/gif)
#~ You can set the gif record time as argument: ./gif 10
#~ Default record time is 1 seconde, or set it now:
   $recordTime = 1;
#~ ----------------

$t = @$argv[1];

if (!isset($argv[1])) {
  $t = $recordTime;
}

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

$p1 = system("xdotool getmouselocation");

$pos1 = explode(" ",$p1);

$x1 = $pos1[0];
$x1 = explode(":",$x1);
echo "X1: ".$x1[1];

$y1 = $pos1[1];
$y1 = explode(":",$y1);
echo " Y1: ".$y1[1];

echo "\nNow move your mousse at the bottom right corner.\nThen enter\n";

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

$p2 = system("xdotool getmouselocation");

$pos2 = explode(" ",$p2);

$x2 = $pos2[0];
$x2 = explode(":",$x2);
echo "X2: ".$x2[1];

$y2 = $pos2[1];
$y2 = explode(":",$y2);
echo " Y2: ".$y2[1];

$gw = ($x2[1] - $x1[1]);
echo "\nGif width: ".$gw;

$gh = ($y2[1] - $y1[1]);
echo "\nGif height: ".$gh;

$unix =  date_timestamp_get(date_create());

echo "\n".$unix." | Starting gif record for ".$t."s\n";

@system("byzanz-record --duration=$t --x=$x1[1] --y=$y1[1] --width=$gw --height=$gh ~/Pictures/gif$unix.gif");

$named = "gif".$unix;

echo "Gif saved\n";

echo "\nOptimize | How many colors to keep? (default 100) \n";

$stdin = fopen('php://stdin', 'r');
$defc = "100";
$response = rtrim(fgets(STDIN));
$defc += $response;

echo "\n";

@system("gifsicle --verbose -i ~/Pictures/$named.gif -O5 --colors=$defc -o ~/Pictures/$named\_reduced.gif");

echo "\nOptimize | Resize width in pixels (default 300px) \n";

$stdin = fopen('php://stdin', 'r');
$rw = "300";
$response = rtrim(fgets(STDIN));

$rw += $response;

echo "\n";

@system("gifsicle --verbose -i ~/Pictures/$named\_reduced.gif --resize-width $rw -o ~/Pictures/".$named."_optimized.gif");

$opt = "~/Pictures/".$named."_optimized.gif";

echo "\nSpecial | Reverse and merge?\n";

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

@system("gifsicle -i ~/Pictures/$named\_reduced.gif '#-2-1' -o ~/Pictures/".$named."_reversed.gif");

$rev = "~/Pictures/".$named."_reversed.gif";

usleep(400000);

@system("gifsicle -i ~/Pictures/$named\_reduced.gif --append $rev --resize-width $rw -o ~/Pictures/".$named."_merged.gif");

usleep(200000);

system("xdg-open ~/Pictures/".$named."_merged.gif");

echo "\nUpload to giphy?\n";

$stdin = fopen('php://stdin', 'r');
$response = rtrim(fgets(STDIN));

$m = "~/Pictures/".$named."_merged.gif";
$f = system("du -h $m");
$f = explode("	",$f);
$f = $f[1];

$www = system('curl --progress-bar -v -F "file=@'.$f.'" -F "api_key=dc6zaTOxFJmzC"  "http://upload.giphy.com/v1/gifs"');

$www = json_decode($www);

echo "\n\nhttps://i.giphy.com/".$www->data->id.".gif\n";

echo "\nThanks YOU!\n";
